### ISSUE TITLE
API

### ISSUE THREAD

**Issue by hcutler** [nchah/knowledge-graph-api#1]
I generated an API key on the Google Developers site, but it isn't working. How did you generate yours, and then did you just store it in a file '.api_key' ?

Thanks!

**Comment by nchah** [comment]
Hello!
To generate the API key, I followed the steps in:
- https://support.google.com/googleapi/answer/6158857?hl=en
- https://support.google.com/googleapi/answer/6158862?hl=en

There may be some further steps needed in enabling this API as well:
- https://support.google.com/googleapi/answer/6158841?hl=en

And yes, I stored the API in a ".api_key" file and added it to .gitignore. It would be even more secure to  store this elsewhere as per https://support.google.com/googleapi/answer/6310037?hl=en but this was a quick script I wrote for a hackathon :)

Hope this helps!
